stages:
  - build
  - test
  - docker-build
  - deploy

# Image de base avec Maven + JDK 17
image: maven:3.9.6-eclipse-temurin-17

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_DRIVER: overlay2

cache:
  paths:
    - .m2/repository
    - target/

# Service PostgreSQL pour les tests d’intégration
services:
  - name: postgres:17
    alias: bank_db
    variables:
      POSTGRES_DB: bankdb
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: admin

# Étape 1 : Compilation
build-job:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests

# Étape 2 : Tests unitaires et d’intégration
test-job:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test
  variables:
    SPRING_PROFILES_ACTIVE: ci
    DATABASE_URL: jdbc:postgresql://bank_db:5432/bankdb
    DATABASE_USERNAME: bankuser
    DATABASE_PASSWORD: admin

# Étape 3 : Construction de l’image Docker
docker-build-job:
  stage: docker-build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
