spring.application.name=bank-account

spring.datasource.url=jdbc:postgresql://localhost:5432/bankdb
spring.datasource.username=bankuser
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=none
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

spring.jpa.properties.hibernate.default_schema=public
spring.liquibase.default-schema=public
spring.liquibase.liquibase-schema=public
